name: Magisk Build

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "build.py"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build-release:
    name: Build release APK (arm64)
    runs-on: macos-26
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build release
        run: ./build.py -vr all

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: magisk-release
          path: out
          compression-level: 9
